#server port
server:
  port: 80
#spring
spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql:///dbpms?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
  thymeleaf:
    cache: false
    prefix: classpath:/templates/modules/
  aop:
    proxy-target-class: false
  task:
    execution:
      pool:
        core-size: 8
        max-size: 256
        keep-alive: 60s
        queue-capacity: 256
      thread-name-prefix: db-service-thread-
#mybatis
mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
#log
logging:
  level:
    com.cy: debug